# Generated by Django 3.1.6 on 2021-04-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='name',
            new_name='serverby',
        ),
    ]
