# Generated by Django 2.0.1 on 2021-01-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productcatergory',
        ),
        migrations.DeleteModel(
            name='catergory',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
