# Generated by Django 2.0.1 on 2021-01-11 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodies', '0002_auto_20210111_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('date_created', models.DateField()),
                ('productcatergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodies.catergory')),
            ],
        ),
    ]
