# Generated by Django 2.0.1 on 2021-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0003_catergory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
