# Generated by Django 2.0.1 on 2021-01-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0004_auto_20210111_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
