# Generated by Django 2.0.1 on 2021-01-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodies', '0005_auto_20210111_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
